# Generated by Django 4.2.7 on 2023-12-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'permissions': (), 'verbose_name': 'technician', 'verbose_name_plural': 'technicians'},
        ),
    ]
