# Generated by Django 4.2.7 on 2024-01-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0005_order_confirmed_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed_assignment',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_confirmation',
            field=models.IntegerField(choices=[(0, 'Sin confirmar'), (1, 'En espera'), (2, 'Confirmada')], default=0, verbose_name='Confirmación Cliente'),
        ),
    ]
