# Generated by Django 4.2.7 on 2024-01-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0006_remove_order_confirmed_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Servicio Activo'),
        ),
    ]
